pipeline:
  name: test pipeline
  identifier: test_pipeline
  projectIdentifier: adithya_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsv
        identifier: dsv
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fds
                  identifier: fds
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression sdfgsd
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
