pipeline:
  name: test trigger repo
  identifier: test_trigger_repo
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: l
        identifier: l
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: jih
                  identifier: jih
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information asd delegate
                      and approve the pipeline progression de sdf fdg as sdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
