pipeline:
  name: triggere piper
  identifier: triggere_piper
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdaf
        identifier: sdaf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: asfd
                  identifier: asfd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression asdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
